### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by jherman3** [ThomasMonkman/filewatch#19]
Great library!

Is there any work being done to support Mac, and if not, would you be willing to accept PRs adding MacOS support?

**Comment by ThomasMonkman** [comment]
Thank you, I don't have a mac to test on, I think it could be added to the ci.

If mac uses the same posix apis as Linux for file watching, it should work. 

Happy to except PRs.

**Comment by pinguin999** [comment]
It's not working on MacOS out of the box. I guess the best way would be to use kqueue https://www.freebsd.org/cgi/man.cgi?kqueue

**Comment by ThomasMonkman** [comment]
Very late on the reply, but someone just did a pr for mac, hopefully this works for both of you.
https://github.com/ThomasMonkman/filewatch/pull/32

if it doesn't please let me know
