### ISSUE TITLE
How to stop the file watcher?

### ISSUE THREAD

**Issue by ZaWarudo111** [ThomasMonkman/filewatch#30]
I want to stop watching a directory, for example i am watching `C:\test\someFolder`, and i want to stop watching it and start watching `C:\another\test` 

so how could I do it?

**Comment by robiwano** [comment]
Just delete the FileWatcher object, and create a new one?

**Comment by ThomasMonkman** [comment]
yes @ZaWarudo111, @robiwano is right, the library follow cpp raii pattern, construction of the class start, destruction ends, if you want fined grained control over this, create the object with an smart pointer.

of course I would probably accept a pr to allow changing a watched dir during object life time.
