### ISSUE TITLE
Filewatch fails to build after latest pull-request

### ISSUE THREAD

**Issue by drsnuggles8** [ThomasMonkman/filewatch#37]
Because of the new line `add_subdirectory(example)` in the main CMakeLists.txt, filewatch fails to build as one of my dependencies. The example's CMakeLists.txt has a `target_include_directories(main PRIVATE ${CMAKE_SOURCE_DIR})` that sets some include directory, but when filewatch is included as a library/dependency, this does not add the right directory, and hence main.cpp has a fatal  error C1083: Cannot open include file: 'FileWatch.hpp' for me.

Easy fix would be to remove the `add_subdirectory(example)`, or use something else than ${CMAKE_SOURCE_DIR} (maybe ${CMAKE_CURRENT_SOURCE_DIR}?).

**Comment by ThomasMonkman** [comment]
ahhh damn, yes when I originally built the project I intended it to be just be a copy and paste job of the filewatch.hpp file, but yes really the cmake needs to be set up in a digestible way.

I'll quickly remove the add_subdirectory stuff

**Comment by ThomasMonkman** [comment]
Should be fixed now @drsnuggles8

**Comment by drsnuggles8** [comment]
Yes exactly, with FetchContent. I've managed to get it working locally by using `target_include_directories(main PRIVATE ${PROJECT_SOURCE_DIR})` in the examples/CMakeLists.txt.

**Comment by drsnuggles8** [comment]
Thanks for the quick help. Working locally with your fix now, re-started the Github Actions build now

**Comment by ThomasMonkman** [comment]
No worries, I think this will prompt me to to looking at getting this digestible from cmake more easily while still having private tests.

At the moment it seems like I also set tons of CMAKE_CXX_FLAGS flags, however I don't know if they are scoped to the projects, or can leak out.

I think I can at least expose it as something like
`add_library(FileWatch INTERFACE FileWatch.hpp)`
