### ISSUE TITLE
The removed even is not triggered when a folder is deleted. 

### ISSUE THREAD

**Issue by SC5Shout** [ThomasMonkman/filewatch#40]
Having this hierarchy
 - New Folder
 - -  Inner Folder

when Inner Folder is deleted, the modified event on New Folder is triggered.  I believe the "removed" event also should be activated. 

```cpp
filewatch::FileWatch<std::string> watch{"./project",
    [this](const std::filesystem::path& path, const filewatch::Event event) {
        const auto workingPath = AssetManager::ASSET_PATH / path;
        if(std::filesystem::is_directory(workingPath)) {
            std::cout << filewatch::event_to_string(event) << "\n";
        }
    } 
};
````

It may be because of the folder is already removed: `if(std::filesystem::is_directory(workingPath))` at this point. I'm not sure, though.

**Comment by SC5Shout** [comment]
Yup, it's because the folder is already deleted when `if` is called.

**Comment by ThomasMonkman** [comment]
Ahh thank you for the follow up check :)
